# Generated by Django 2.2 on 2019-09-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.TextField()),
                ('dataCompra', models.TextField()),
                ('valorCompra', models.TextField()),
                ('quantidade', models.TextField()),
                ('taxa', models.TextField()),
                ('totalCompra', models.TextField()),
                ('dataVenda', models.TextField()),
                ('valorVenda', models.TextField()),
            ],
        ),
    ]
