# Generated by Django 2.2 on 2019-09-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.TextField()),
                ('nome', models.TextField()),
                ('setor', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dividendos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.TextField(verbose_name='Carteira')),
                ('dataDividendo', models.TextField()),
                ('dataPagamento', models.TextField()),
                ('dividendos', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='totalCompra',
        ),
        migrations.AlterField(
            model_name='transacao',
            name='dataCompra',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='dataVenda',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='ticker',
            field=models.TextField(verbose_name='Carteira'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='valorCompra',
            field=models.PositiveIntegerField(),
        ),
    ]
