# Generated by Django 2.2 on 2019-09-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0002_auto_20190924_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividendos',
            name='ticker',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='ticker',
            field=models.TextField(),
        ),
    ]
