# Generated by Django 2.2 on 2019-09-24 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0005_auto_20190924_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteira',
            name='ticker',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='dividendos',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carteira.Carteira'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carteira.Carteira'),
        ),
    ]
