# Generated by Django 2.2 on 2019-09-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0006_auto_20190924_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='dataVenda',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='valorVenda',
            field=models.TextField(null=True),
        ),
    ]
