# Generated by Django 2.2 on 2019-09-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0007_auto_20190924_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='dataVenda',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='valorVenda',
            field=models.TextField(blank=True, null=True),
        ),
    ]
