# Generated by Django 2.2 on 2019-09-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0009_auto_20190925_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividendos',
            name='ticker',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='ticker',
            field=models.SlugField(unique=True),
        ),
    ]
