# Generated by Django 2.2 on 2019-09-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0010_auto_20190925_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteira',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carteira',
            name='setor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carteira',
            name='tipo',
            field=models.CharField(default='Ação', max_length=50),
        ),
    ]
