# Generated by Django 2.2 on 2019-10-02 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0012_carteira_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividendos',
            name='carteira',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carteira.Carteira'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='carteira',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carteira.Carteira'),
        ),
        migrations.AlterField(
            model_name='dividendos',
            name='dataDividendo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dividendos',
            name='dataPagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dividendos',
            name='ticker',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='ticker',
            field=models.SlugField(),
        ),
    ]
