# Generated by Django 2.2 on 2019-10-03 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0013_auto_20191002_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.SlugField(unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('setor', models.CharField(max_length=50)),
                ('tipo', models.CharField(default='Ação', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='dividendos',
            name='carteira',
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='carteira',
        ),
        migrations.AlterField(
            model_name='dividendos',
            name='ticker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carteira.Ticker'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='ticker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carteira.Ticker'),
        ),
        migrations.DeleteModel(
            name='Carteira',
        ),
    ]
