# Generated by Django 2.2 on 2019-10-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0014_auto_20191003_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
