# Generated by Django 2.2 on 2019-10-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0015_auto_20191008_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='quantidade',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
    ]
