# Generated by Django 2.2 on 2019-10-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0016_auto_20191008_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='valorCompra',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
